namespace GBS.Api.DbModels
{
    public partial class GBS_DbContext
    {
        public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
        {
            // First save to get the generated IDs
            var result = await base.SaveChangesAsync(cancellationToken);

            // Generate reference numbers for newly added entities
            var hasUpdates = GenerateReferences();

            if (hasUpdates)
            {
                // Save again to persist the reference numbers
                await base.SaveChangesAsync(cancellationToken);
            }

            return result;
        }

        public override int SaveChanges()
        {
            // First save to get the generated IDs
            var result = base.SaveChanges();

            // Generate reference numbers for newly added entities
            var hasUpdates = GenerateReferences();

            if (hasUpdates)
            {
                // Save again to persist the reference numbers
                base.SaveChanges();
            }

            return result;
        }

        private bool GenerateReferences()
        {
            bool hasUpdates = false;

            //Clients
            var clientsWithoutRef = Clients
                .Where(c => c.Id > 0 && string.IsNullOrEmpty(c.Reference))
                .ToList();

            foreach (var client in clientsWithoutRef)
            {
                client.Reference = GenerateRefNumber("Clients", client.Id);
                hasUpdates = true;
            }


            //Clients
            var employeesWithoutRef = Employees
                .Where(c => c.Id > 0 && string.IsNullOrEmpty(c.Reference))
                .ToList();

            foreach (var employee in employeesWithoutRef)
            {
                employee.Reference = GenerateRefNumber("Employees", employee.Id);
                hasUpdates = true;
            }


            // Payments
            var paymentsWithoutRef = Payments
                .Where(p => p.Id > 0 && string.IsNullOrEmpty(p.Reference))
                .ToList();

            foreach (var payment in paymentsWithoutRef)
            {
                payment.Reference = GenerateRefNumber("Payments", payment.Id);
                hasUpdates = true;
            }

            // Products
            var productsWithoutRef = Products
                .Where(p => p.Id > 0 && string.IsNullOrEmpty(p.Reference))
                .ToList();

            foreach (var product in productsWithoutRef)
            {
                product.Reference = GenerateRefNumber("Products", product.Id);
                hasUpdates = true;
            }

            // Orders
            var ordersWithoutRef = Orders
                .Where(o => o.Id > 0 && string.IsNullOrEmpty(o.Reference))
                .ToList();

            foreach (var order in ordersWithoutRef)
            {
                order.Reference = GenerateRefNumber("Orders", order.Id);
                hasUpdates = true;
            }

            return hasUpdates;
        }

        private static string GenerateRefNumber(string module, int id)
        {
            string formattedId = id.ToString("D6");
            string moduleUpper = module.Trim().ToUpper();

            return moduleUpper switch
            {
                "PAYMENTS" => $"PMT{formattedId}",
                "CLIENTS" => $"CLT{formattedId}",
                "PRODUCTS" => $"PRD{formattedId}",
                "ORDERS" => $"ORD{formattedId}",
                "MATERIALS" => $"MAT{formattedId}",
                "EMPLOYEES" => $"EMP{formattedId}",
                _ => $"{moduleUpper[..3]}{formattedId}"
            };
        }
    }
}
//```

//---

//## Project Structure
//```
//GBS.Entities /
//├── DbModels /
//│   ├── GBS_DbContext.cs           ← Generated by scaffold (don't modify)
//│   ├── GBS_DbContextExtensions.cs ← Your custom partial class (safe from regeneration)
//│   ├── Client.cs                  ← Generated
//│   ├── Payment.cs                 ← Generated
//│   ├── Product.cs                 ← Generated
//│   ├── Order.cs                   ← Generated
//│   └── ... other entities